services:
  tender_bot:
    build: .
    image: tender_bot
    container_name: tender_bot
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
